name: Publish package to npmjs

on:
  push:
    branches:
      - main
      - next
      - beta
    paths-ignore:
      - '.github/**'

env:
  NODE_AUTH_TOKEN: ${{ secrets.GH_READ_TOKEN }}

permissions: write-all

concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  build:
    name: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: release
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
